language: objective-c
osx_image: xcode11
install:
  - brew install swiftformat
  - brew install swiftlint
script:
  - gem install travis
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build -project TypographyKitPalette.xcodeproj -scheme TypographyKitPalette -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
